database:
  path: data/articles.sqlite

sites:
  - name: happytimes
    url: https://happytimes.info
    fetcher: requests
  - name: dzen
    url: https://dzen.ru/id/verynevery
    fetcher: playwright
  - name: dzen
    url: https://dzen.ru/radostislezi
    fetcher: playwright
  - name: dzen
    url: https://dzen.ru/id/69eb5ea6fea93431608a3429
    fetcher: playwright
